feat: 문자열계산기 패키지 분리 , 로또 구현
hhlyn0328/lotto-practice pull request #5
Opened 2021-01-08 04:49 UTC by updown-kurly

2021-01-08 07:10 UTC, hhlyn0328 requested changes
전체적으로 객체 책임 분리나 어플리케이션의 흐름이 많이 좋아지신 거 같아요 👍 
제가 받았던 코멘트들을 포함해서 몇가지 피드백 드렸습니다 
이번 미션도 화이팅입니당 !

2021-01-08 07:10 UTC, hhlyn0328 commented on src/main/java/lotto/LottoApplication.java
> +    public static void main(String[] args) {
main 로직에서 이전에 비해 많이 간결해진 흐름이 느껴집니다 👍

2021-01-08 07:10 UTC, hhlyn0328 commented on src/main/java/lotto/InputView.java
> +    public static int isOneToFortyFiveNumber(Integer lottoNumber) {
InputView는 숫자를 입력받을 뿐이고 이게 유효한 로또 숫자인지는 
LottoNumber가 판단하도록 하면 어떨까요?
InputView, ResultView에는 가능한 테스트 가능한 비즈니스 로직이 없어야합니다.

2021-01-08 07:10 UTC, hhlyn0328 commented on src/main/java/lotto/LottoNumber.java
> +public class LottoNumber {
1-45까지 있는 배열을 로또 티켓만큼 생성하고 있네요
LottoNumberGenerator 라는 유틸성 클래스를 만들어서 로또숫자생성 부분만 분리해 보면 어떨까요? 
LottoNumber는 validation 로직만 가지고 있어도 될 거 같네요

2021-01-08 07:10 UTC, hhlyn0328 commented on src/main/java/lotto/LottoNumbers.java
> +    public void setLottoNumbers(List<LottoNumber> lottoNumbers) {
setter는 가급적 사용하지 않는 것이 좋습니다 
List<LottoNumber> lottoNumbers 를 인자로 받는 생성자를 추가하면 어떨까요?
new LottoNumbers() + setLottoNumbers  의 반복 로직도 더 단순해질 것 같아요

2021-01-08 07:10 UTC, hhlyn0328 commented on src/main/java/lotto/LottoNumbers.java
> +public class LottoNumbers {
일급컬렉션 사용 👍

2021-01-08 07:10 UTC, hhlyn0328 commented on src/main/java/lotto/LottoResult.java
> +        initMatchCount(winnerLottoNumber, lottoNumber);
Init을 사용하니 기본값으로 초기화 할 것 같아요 match, calculate 로 시작하는게 어떨까요?

2021-01-08 07:10 UTC, hhlyn0328 commented on src/main/java/lotto/LottoResult.java
> +    public LottoResult(List<Integer> winnerLottoNumber, LottoNumber lottoNumber) {
당첨번호도 일급컬렉션으로 사용해 볼 수 있지 않을까요? 
당첨번호 일급컬렉션에서 로또번호를 전달받아 당첨번호와 비교 후 LottoResult를 반환할 수도 있겠네요!

2021-01-08 07:10 UTC, hhlyn0328 commented on src/main/java/lotto/LottoResult.java
> +                filter(i -> lottoNumber.getLottoNumber().contains(i)).
get으로 속성을 가져와 비교하는 것보다 LottoNumber에게 질문을 던져 보면 어떨까요?
'이 숫자 가지고 있니?'

2021-01-08 07:10 UTC, hhlyn0328 commented on src/main/java/lotto/LottoTotalResult.java
> +            if (lottoResult.getMatchCount() == 3) {
indent는 1 이상이 되면 안된다.
LottoResult 결과에 대한 처리를 분리해보면 좋을 거 같습니다

2021-01-08 07:10 UTC, hhlyn0328 commented on src/main/java/lotto/LottoTotalResult.java
> +        float totalWinningAmount = lottoResultList.stream().mapToInt(LottoResult::getWinningAmount).sum();
위의 LottoResult 에 대해 count++ 하는 로직에서 totalWinningAmount 도 구할 수 있지 않을까요?

2021-01-08 07:10 UTC, hhlyn0328 commented on src/main/java/lotto/ResultView.java
> +        System.out.println("6개 일치 (2000000000원)- " + lottoTotalResult.getSixMatchCount() + "개");
금액이 변경되면 ResultView 와 LottoResult가 모두 수정되어야겠네요? 
한 쪽만 수정할 수 있도록 변경해볼까요? ㅎㅎ

2021-01-08 07:10 UTC, hhlyn0328 commented on src/main/java/lotto/ResultView.java
> +            System.out.println(Arrays.toString(
LottoNumber 의 toString을 구현해보면 좋을거 같아요 :)

2021-01-08 07:10 UTC, hhlyn0328 commented on src/main/java/lotto/LottoTotalResult.java
> +        initReturnRate(lottoResultList);
initMatchCounts 의 return type을 List<LottoResult> 로 선언하고 
`initReturnRate(initMatchCounts(winnerNumber, lottoNumbers));`
위처럼 하는게 더 좋을 거 같습니다 callbyreference로 다른 곳에 수정을 위임하는것은 가급적 사용하지 않도록 하는게 좋다고 하네요

2021-01-08 07:10 UTC, hhlyn0328 commented on src/main/java/lotto/LottoNumber.java
> +    public static final List<Integer> LOTTO_BASE_NUMBER = Arrays.asList(
static 블락 이라는 것이 있습니다 
1 - 45를 나열하는것보다 깔끔하게 초기화가 가능하니 한 번 검색해보시고 반영해보시면 좋을 거 같아요

2021-01-09 08:15 UTC, hhlyn0328 requested changes
피드백 반영 잘해주셨습니다 
지금도 좋은데 조금 더 다듬으면 더 명확해질 부분에 대해 고민해볼만한 코멘트를 추가했으니 
한 번 더 고민해봐주세요 :) 

이번 미션에서 구조를 잘 잡아야 뒤의 미션에서 뒤집어 엎지 않아도 되기 때문에
피드백이 어쩔 수 없이 제일 많은 미션이 될 거에요 
모두가 그런 것 이므로 절대 좌절 금지!!

2021-01-09 08:15 UTC, hhlyn0328 commented on src/main/java/lotto/LottoNumberGenerator.java
> +    static {
훨씬 깔끔하네요! 👍 
만약에 로또 번호가 65까지 늘어난다고 했을 때 이전보다 잘 대응할 수 있을 것 같아요 ㅎㅎ

2021-01-09 08:15 UTC, hhlyn0328 commented on src/main/java/lotto/LottoNumbers.java
>      public LottoNumbers() {
인자가 없는 생성자가 사용되지 않는다면 
부분별한 객체 생성을 막기 위해 protected나 private으로 생성자 접근을 제한하면 어떨까요?

2021-01-09 08:15 UTC, hhlyn0328 commented on src/main/java/lotto/LottoResult.java
> +                filter(i -> lottoNumber.isContains(lottoNumber, i)).
lottoNumber에게 물어보는데 lottoNumber를 다시 전달해줄 필요가 있을까요?
클래스 함수와 인스턴스 함수의 차이를 고민해보시면 좋을거 같아요

2021-01-09 08:15 UTC, hhlyn0328 commented on src/main/java/lotto/LottoTotalResult.java
> +        this.totalWinningAmount = this.totalWinningAmount + lottoResult.getWinningAmount();
+= 으로 간단하게 표현해도 될 것 같아요 ㅎㅎ

2021-01-09 08:15 UTC, hhlyn0328 commented on src/main/java/lotto/LottoWinnerNumber.java
> +    private List<Integer> lottoWinnerNumber;
우승자 번호도 LottoNumber를 변수로 가질 수 있지 않을까요?
우승자 번호가 체크해야하는 validation 로직이 결국은 로또번호의 유효성과 일치 할 것 같아요 
1-45 사이의 숫자여야하고, 정렬되어야하고, 중복이 없어야 한다는 것

그럼 객체 구조를 가져가는 방법이 2개가 될 수 있을 거 같아요 
현재 구조에서 LottoWinnerNumber 에서 단일 LottoResult의 계산을 처리하고 
로또번호를 당첨번호에게 나 이거 몇개나 맞았어? 하고 물어보는거죠 
로또번호에게 당첨번호는 이건데, 너는 몇개나 맞았어? 와 비교해봤을 때 기준이 어떤게 되는게 맞는지 고민해보시면 좋을거 같아요 

그럼 LottoResult 를 생성하는 주체는 LottoWinnerNumber가 되고, 
LottoResult는 이전에 RacingResult처럼 결과에 대한 접근만 제공하겠죠?

2021-01-09 08:15 UTC, hhlyn0328 commented on src/main/java/lotto/LottoWinnerNumber.java
> +            if (lottoNumber <= 0 || lottoNumber > 45) {
이 validation에서도 기준점이 상수로 선언되면 좋겠네요 :) 
현재는 당첨번호가 4,4,4,4,4,4 라고 입력해도 통과될 것 같네요 !

2021-01-09 08:15 UTC, hhlyn0328 commented on src/main/java/lotto/ResultView.java
> +        System.out.println("3개 일치 (" + LottoResult.THREE_MATCH_AMOUNT + "원)- " + lottoTotalResult.getThreeMatchCount() + "개");
'+' 연산으로 String을 조합하는 것도 좋지만 
String.format("3개 일치 (%d원)- %d개", LottoResult.THREE_MATCH_AMOUNT, lottoTotalResult.getThreeMatchCount())

형식으로 표현하면 내부의 변수가 많아지거나 변수명이 길어졌을 때, 그래도 표현하고자 하는 문자열의 식별이 더 쉬울 것 같아요

2021-01-09 08:15 UTC, hhlyn0328 commented on src/test/java/lotto/LottoWinnerNumberTest.java
> +class LottoWinnerNumberTest {
👍

2021-01-09 08:15 UTC, hhlyn0328 commented on src/test/java/lotto/LottoTotalResultTest.java
> +        List<LottoNumber> lottoNumbers = new ArrayList<>();
👍

2021-01-09 08:15 UTC, hhlyn0328 commented on src/main/java/lotto/LottoNumber.java
> +        this.lottoNumber = LottoNumberGenerator.createLottoNumber();
현재는 인자가 없는 생성자로 생성할 경우에는 자동 번호가 생성되고 
번호를 직접입력할 경우 수동 번호가 생성되고 있는데 
인자가 없을 경우 자동으로 생성됨을 흐름상 쉽게 파악할 수 있을까요?
외부에서 생성해서 전달해주어 아래 로직으로 생성되는 것을 통일 시키면 어떨까요?
`public LottoNumber(List<Integer> lottoNumber)`

현재 로또넘버 자체에 대한 validation은 LottoNumberGenerator를 믿고 아무것도 진행되지 않는 것 같아요
현재 아무거나 입력해서 생성하는 구조인데 그렇게 생성된 인스턴스도 LottoNumber의 인스턴스라고 부를 수 있을까요?

2021-01-11 01:51 UTC, updown-kurly commented on src/main/java/lotto/ResultView.java
> +        System.out.println("3개 일치 (" + LottoResult.THREE_MATCH_AMOUNT + "원)- " + lottoTotalResult.getThreeMatchCount() + "개");
헛 이런 세세한 부분까지 감사합니다 다음에는 이런거까지 신경써서 올리겠습니다🙏

2021-01-11 04:22 UTC, updown-kurly commented on src/main/java/lotto/LottoWinnerNumber.java
> +    private List<Integer> lottoWinnerNumber;
이부분을 해결하기 위해 LottoNumberValidation 클래스를 분리하여 static 으로 올려 validation 검사를 할수 있도록 하였는데 이방법은 올바른 방법이 아닌건가요?

2021-01-12 14:56 UTC, hhlyn0328 requested changes
몇가지 추가 코멘트 드렸어요 
참고해주세용 -

2021-01-12 14:56 UTC, hhlyn0328 commented on src/main/java/lotto/LottoNumberGenerator.java
> +        for (int i = 0; i < 6; i++) {
6도 상수로 선언되면 좋겠네요 ㅋㅋㅋ

2021-01-12 14:56 UTC, hhlyn0328 commented on src/main/java/lotto/LottoNumberValidation.java
> +    public static List<Integer> isValidation(List<Integer> lottoNumber) {
6자리인지도 체크해보면 좋을거 같네요 
당첨번호가 [1] 도 가능할 거 같아요

2021-01-12 14:56 UTC, hhlyn0328 commented on src/main/java/lotto/LottoNumbers.java
> +            this.lottoNumbers.add(new LottoNumber(LottoNumberGenerator.createLottoNumber()));
LottoNumberGenerator 에서 LottoNumber type 으로 return 하면 어떨까요?
이 로직이 더 깔끔해질 것 같아요 !

2021-01-12 14:56 UTC, hhlyn0328 commented on src/main/java/lotto/LottoResult.java
> +                filter(lottoWinnerNumberEach -> lottoNumber.isContains(lottoWinnerNumberEach)).
해당 표현이 람다 표현식에 따라서 아래처럼 표현 가능 할 거 같아요
`lottoNumber::isContains `

클래스 함수는 LottoNumber::isContains 지만, 인스턴스 함수는 미리 생성되어있다면 위처럼 쓸 수 있는거 같아요 
인자가 0개거나 1개까지는 자동변환해주는거 같습니다

그리고 스트림뒤에 점은 아래로 내려오는게 가독성이 더 좋을거 같습니다

2021-01-12 14:56 UTC, hhlyn0328 commented on src/main/java/lotto/LottoTotalResult.java
> +        for (LottoNumber lottoNumber : lottoNumbers.getLottoNumbers()) {
계속 코드리뷰를 받다보니까 클린코드는 일단 다른 인스턴스에서 get한 값을 쓰는걸 
정말 어쩔 수 없는 경우를 빼고는 지양하는거 같아요 
그렇기 때문에 보통 이런건 lottoNumbers 에게 해당기능을 위임할 수 있지 않을까요 -? 라고 하죠

List<LottoResult> lottoResultList 를 반환하도록요 :)

2021-01-12 14:56 UTC, hhlyn0328 commented on src/main/java/lotto/LottoTotalResult.java
> +        if (lottoResult.getMatchCount() == 3) {
그런경우도 get해서 비교하기 보다는 
lottoResult.isMatchCount(3) 과 같이 객체에게 물어보면 어떨까요?

2021-01-12 14:56 UTC, hhlyn0328 commented on src/main/java/lotto/ResultView.java
> +        System.out.println(lottoNumbers.getLottoNumbers().size() + "개를 구매했습니다.");
객체지향 생활체조 한라인에 .을 2개 찍지 않는다 
사이즈를 가져오는 method를 추가해보시죠

2021-01-12 14:56 UTC, hhlyn0328 commented on src/main/java/lotto/LottoWinnerNumber.java
> +    public List<Integer> isOneToFortyFiveNumber(List<Integer> lottoWinnerNumber) {
method 명이 isOneToFortyFiveNumber 만 체크할 거 같네요

2021-01-13 01:35 UTC, updown-kurly commented on src/main/java/lotto/LottoWinnerNumber.java
> +    private List<Integer> lottoWinnerNumber;
LottoNumber 안에 validation 로직을 넣고 몇 개 맞았는지 & 당첨금액 로직을 winnerLottoNumber 에 넣었는데
이렇게되면 LottoResult 가 하는일이 없어져서 이렇게 가는게 당첨금액은 안넣는게 맞는걸까요??

2021-01-13 01:36 UTC, updown-kurly commented on src/main/java/lotto/LottoNumberGenerator.java
> +        for (int i = 0; i < 6; i++) {
넵

2021-01-13 01:40 UTC, updown-kurly commented on src/main/java/lotto/LottoNumberValidation.java
> +    public static List<Integer> isValidation(List<Integer> lottoNumber) {
넵

2021-01-13 01:41 UTC, updown-kurly commented on src/main/java/lotto/LottoNumbers.java
> +            this.lottoNumbers.add(new LottoNumber(LottoNumberGenerator.createLottoNumber()));
넵

2021-01-13 01:45 UTC, updown-kurly commented on src/main/java/lotto/LottoResult.java
> +                filter(lottoWinnerNumberEach -> lottoNumber.isContains(lottoWinnerNumberEach)).
넵

2021-01-13 01:46 UTC, updown-kurly commented on src/main/java/lotto/ResultView.java
> +        System.out.println(lottoNumbers.getLottoNumbers().size() + "개를 구매했습니다.");
넵

2021-01-13 01:46 UTC, updown-kurly commented on src/main/java/lotto/ResultView.java
> +        System.out.println(lottoNumbers.getLottoNumbers().size() + "개를 구매했습니다.");
Resolve conversation 안누르고 넵으로 체크하고 있습니다..ㅋㅋ

2021-01-13 01:48 UTC, updown-kurly commented on src/main/java/lotto/LottoWinnerNumber.java
> +    public List<Integer> isOneToFortyFiveNumber(List<Integer> lottoWinnerNumber) {
요건 삭제 되었습니다.

2021-01-13 03:38 UTC, updown-kurly commented on src/main/java/lotto/LottoTotalResult.java
> +        if (lottoResult.getMatchCount() == 3) {
넵

2021-01-13 05:09 UTC, updown-kurly commented on src/main/java/lotto/LottoTotalResult.java
> +        for (LottoNumber lottoNumber : lottoNumbers.getLottoNumbers()) {
혜린님 이부분을 lottoNumbers에 넘겨서 작성해 봤는데 그러면 for문 안에서 도는 
            calculateTotalWinningAmount(lottoResult);
            calculateMatchCount(lottoResult);
이 두가지 로직도 LottoNumbers 로 옮겨지게 되고 그러면 LottoResult 에서 get을 사용해서
계산된 값을 가져와야 할것 같은데 어떻게 풀어나가야 할까요?

2021-01-13 08:28 UTC, hhlyn0328 reviewed
PR 전 고민하셨던 부분은 구현하신게 제가 공유드린 내용과 맞습니다 :) 
다음이 마지막 PR이 되실 것 같은 느낌이 듭니다 
조금만 더 힘을 내주세요 !

2021-01-13 08:28 UTC, hhlyn0328 commented on src/main/java/lotto/LottoNumbers.java
> +            LottoResult lottoResult = new LottoResult(lottoWinnerNumber, lottoNumber);
객체 자체가 새로 생성되어야 하는 경우와 다른 action에 의해 파생적으로 생성되는 경우를 구분하면 좋을거 같아요

로또 번호는 금액만큼, 입력한대로 그 자체의미로 새로 생성되어야 해서 생성자에 어느 정로 로직이 있지만 
LottoTotalResult 나 LottoResult는 matching 이라는 action의 결과라고 보거든요 

그래서 LottoTotalResult가 그랬듯 이 부분도 new LottoResult 생성자를 호출할게 아니라 
lottoWinnerNumber.isMatchCount(lottoNumber) 의 결과가 LottoResult를 return 하도록 변경해보면 좋을 거 같아요

2021-01-13 08:28 UTC, hhlyn0328 commented on src/main/java/lotto/LottoWinnerNumber.java
> +    private List<Integer> lottoWinnerNumber;
이부분 
private List<Integer> lottoWinnerNumber;
private LottoNumber lottoWinnerNumber;
아래처럼 변경하기로 하지 않았나요?

2021-01-13 08:28 UTC, hhlyn0328 commented on src/main/java/lotto/ResultView.java
> +        System.out.println("총 수익률은 : " + String.format("%.2f",lottoTotalResult.getReturnRate()) + "입니다.");
String.format 을 어차피 사용했다면, 
앞 뒤의 문자열도 formatString 안에 넣을 수 있을 거 같아요

2021-01-13 08:28 UTC, hhlyn0328 commented on src/test/java/lotto/LottoNumberTest.java
> +public class LottoNumberTest {
변경로직에 대한 테스트추가 👍

2021-01-13 08:28 UTC, hhlyn0328 commented on src/test/java/lotto/LottoNumberTest.java
> +    void 번호가_6자리_Exception테스트() {
이렇게 동일한 테스트가 반복되는데 중간의 값만 변경되는 경우 아래와 같은 방법을 사용하면 반복되는 코드를 제거 할 수 있습니다 

```
@ParameterizedTest
@MethodSource("generateData")
void shouldGetDataBit(List<Integer> numbers) {
        assertThatExceptionOfType(IllegalArgumentException.class).isThrownBy(() -> {
            new LottoNumber(numbers);
        });
}

static Stream<Arguments> generateData() {
    return Stream.of(
        Arguments.of(Arrays.asList(1)),
        Arguments.of(Arrays.asList(1, 2))
    );
}
```

2021-01-13 08:28 UTC, hhlyn0328 commented on src/test/java/lotto/LottoTotalResultTest.java
> +        assertThat(String.format("%.2f",lottoTotalResult.getReturnRate())).isEqualTo("0.36");
지금 이 테스트는 등수별 가격이 변동되거나 로또 숫자가 하나라도 추가되면 깨질 거 같은데 
상관없이 유연하게 테스트할 수 있는 방법은 뭐가 있을까요? :)

2021-01-13 09:11 UTC, updown-kurly commented on src/main/java/lotto/ResultView.java
> +        System.out.println("총 수익률은 : " + String.format("%.2f",lottoTotalResult.getReturnRate()) + "입니다.");
private LottoNumber lottoWinnerNumber;로 변경하였습니다


이렇게 되면 아래 메소드에서 get을 또 사용하게 되어
LottoNumber 안으로 옮기려고 했는데 WinnerNumber 에 있는게 맞다고 생각하여 유지했습니다

    public int isMatchCount(LottoNumber lottoNumber) {
        return (int) this.lottoWinnerNumber.getLottoNumber().stream()
                .filter(lottoNumber::isContains)
                .count();
    }

2021-01-13 09:18 UTC, updown-kurly commented on src/test/java/lotto/LottoNumberTest.java
> +    void 번호가_6자리_Exception테스트() {
태어나서 처음보는 문법입니다 감사합니다 ㅋㅋ

2021-01-15 02:01 UTC, eeunheechoi commented on src/main/java/lotto/LottoNumber.java
> +
저는 중복 리스트를 받아 사이즈를 if문에서 비교했는데 그냥 바로 boolean으로 받음 되는군여. 몰랐네요 ㅎㅎ

2021-01-15 02:37 UTC, eeunheechoi approved these changes
저는 반성만 하다 갑니다. 
개선해야 할 점은 아직 저에게 안보이네요.
좀 더 노력하여 도움되는 코멘트를 드릴 수 있도록 하겠습니다.

2021-01-15 02:37 UTC, eeunheechoi commented on src/main/java/lotto/LottoNumbers.java
> +        }
저는 구매 금액을 따로 모델 분리해서 금액 모델에서 검증로직 넣었네요. 참고하세요

2021-01-15 02:37 UTC, eeunheechoi commented on src/test/java/lotto/LottoNumberTest.java
> +    }
@MethodSource를 사용하면 아래 메소드에정의된 리스트들을 테스트 인수 갑으로 하나하나 넘겨 테스트 해주는 건가여?

2021-01-15 02:37 UTC, eeunheechoi commented on src/test/java/lotto/LottoTotalResultTest.java
> +        int inputAmount = this.lottoNumbers.getLottoNumbers().size() * LottoTotalResult.LOTTO_PRICE;
저는 수익률이나 매칭카운트에 대해 테스트는 안했는데.. 저도 해야겠네요. 반성

2021-01-17 01:11 UTC, hhlyn0328 commented on src/test/java/lotto/LottoNumberTest.java
> +    }
@eeunheechoi 네 맞습니다 
`@ ParameterizedTest`  는 야구게임 프리코스에서 학습테스트로 슬쩍 스쳐가셨던 기억이 희미하게 나실거 같은데요 
같은 로직을 테스트데이터만 다르게 반복 수행하는 경우, 코드의 단순 반복을 제거하는 목적으로 사용됩니다.

그 학습테스트 문서에서는 간단하게 기본 타입에 대한 ValueSource 만 나와있었는데요 
`@ValueSource(ints = {1, 2, 5, 10, 11})   /   @ValueSource(strings = {"22", "33"})`
위처럼 source에 있는 하나 하나의 값을 테스트 함수의 parameter로 전달해줘서 Source의 사이즈만큼의 테스트를 수행해줍니다.
보통의 테스트코드는 `test()` 와 같이 parameter 를 받지 않지만 
이 경우에는 `void shouldGetDataBit(List<Integer> numbers) { `처럼 parameter 를 전달 받도록 해야해요

List나 Object 타입의 경우에는 위처럼 표현이 불가능하기 때문에  (가능하다고 해도 가독성이 좋지 않을게 분명할 거 같습니다)
MethodSource 를 통해 source 목록을 생성해줄 수 있습니다.

2021-01-17 01:15 UTC, hhlyn0328 commented on src/test/java/lotto/LottoNumberTest.java
> +    }
상하님 이전 로직입니다.. 이 처럼 반복되는 코드를 개선할 수 있는 방법이쥬 
![image](https://user-images.githubusercontent.com/41069113/104828454-df5d8780-58ac-11eb-9375-591a632ef70d.png)

2021-01-17 01:16 UTC, hhlyn0328 commented on src/test/java/lotto/LottoTotalResultTest.java
> +        int inputAmount = this.lottoNumbers.getLottoNumbers().size() * LottoTotalResult.LOTTO_PRICE;
테스트 코드 누락에 대한 코드리뷰는 리뷰어에게도 쉽지 않아요 😭

2021-01-17 01:20 UTC, hhlyn0328 approved these changes
https://github.com/hhlyn0328/lotto-practice/pull/5/files#r556332689

이 부분만 한 번 확인해봐주시면 좋을 거 같습니다 :) 
다음 커밋에는 머지가시죠

2021-01-18 14:33 UTC, hhlyn0328 approved these changes
:clap
아주 세밀한 네이밍 정도의 코멘트만 달았습니다 
다음 미션에 참고만 해주세요 :)
고생하셨습니다!

2021-01-18 14:33 UTC, hhlyn0328 commented on src/main/java/lotto/LottoWinnerNumber.java
> +        return lottoResult;
return new LottoResult(matchCount);
로 가시죠

2021-01-18 14:33 UTC, hhlyn0328 commented on src/main/java/lotto/LottoTotalResult.java
> -        if (lottoResult.isMatchCount(3)) {
isMatchCountEqualTo 등으로 boolean return 형이라 is 가 앞에 오는게 맞을거 같아요

2021-01-18 14:33 UTC, hhlyn0328 commented on src/main/java/lotto/LottoWinnerNumber.java
> +    public LottoResult isMatchCount(LottoNumber lottoNumber) {
return 타입이 boolean이 아니므로 match 나 matchNumbers 처럼 
숫자 일치를 확인한다는 동사가 앞에 오면 좋겠네요

2021-01-18 14:33 UTC, hhlyn0328 commented on src/main/java/lotto/InputView.java
> +                .map(splitLottoNumberInteger -> Integer.parseInt(splitLottoNumberInteger))
.map(Integer::parseInt)

로 표현할 수 있지 않나요?

2021-01-18 14:34 UTC, merged

2021-01-18 20:49 UTC, updown-kurly commented on src/main/java/lotto/LottoWinnerNumber.java
> +        return lottoResult;
넵!

2021-01-18 20:49 UTC, updown-kurly commented on src/main/java/lotto/LottoTotalResult.java
> -        if (lottoResult.isMatchCount(3)) {
넵!

2021-01-18 20:50 UTC, updown-kurly commented on src/main/java/lotto/LottoWinnerNumber.java
> +    public LottoResult isMatchCount(LottoNumber lottoNumber) {
넵!