로또 기능 구현
hhlyn0328/lotto-practice pull request #6
Opened 2021-01-11 10:50 UTC by eeunheechoi

2021-01-11 15:12 UTC, hhlyn0328 requested changes
👍  이 한 30개 있었는데 코멘트가 너무 많은거 같아서 다 지웠습니다 
전체적으로 객체에 책임을 나눠 위임하는 부분이 많이 좋아지셨네요
특히 상수선언은 이제 코멘트 드릴게 없을 정도로 습관화 되신 것 같아요 💯 

당첨번호와 일치되는 숫자 와 당첨 금액을 enum으로 사용한 점도 좋았습니다 

레이싱 때도 그렇고 첫번째 미션이 기본구조를 잡고 가야하는 부분이라서 제일 피드백이 많은 구간입니다 
코멘트 숫자에 너무 주눅들지 마시고 하나하나 차근차근 봐주세요 

이해가 안되는 코멘트가 있다면 언제든 질문해주세요  :)
화이띵 -

2021-01-11 15:12 UTC, hhlyn0328 commented on src/main/java/lotto/InputView.java
> +        return scanner.nextInt();
Scanner가 입력하는 방식은 키보드의 입력을 우선 내부의 버퍼라는 곳에 다 저장을 한 뒤에
(엔터)를 입력받으면, scanner가 읽는 방식에 따라 처리를 하는데요

로또의 경우 14000 (엔터)  실제로는 이렇게 키보드 입력을 하게 되는데 
nextInt를 하게되면 공백전까지 입력된 숫자를 가져가기 때문에 (엔터)를 제외하고 14000 만 쏙 빼갑니다
그럼 버퍼에 남아있는 (엔터) 가 다음 scan할 때, 
나야!!!! 이번엔 나야!!!! 내가 1등으로 남아있어 !!!! 하게 되는거죠 

그럼 다음에 입력받으려고 했던 기준이 nextLine()으로  (엔터)가 들어올때까지 다 받아! 인데
버퍼에 이미 1등이 아까 입력했던 (엔터) 이기 때문에 다른건 입력받지 않고 끝나는거죠  

은희님이 하신것처럼 스캐너를 별도로 가져서 각각의 버퍼를 가지게 하는 것도 방법이지만 
inputLottoPrice 에서 scanner.nextLine(); 으로 받은 후에 Integer.parseInt 해주는 것도 방법입니다.
nextLine은 (엔터) 까지 가져간다음, 엔터 앞의 대상만 짤라주기 때문이죠
현 상태를 유지하셔도 되지만, 왜 그런 현상이 나왔는지 이해하시고 선택하시면 좋을거 같아서 코멘트 드렸구요 
만약 현상유지 선택시에는 상태 각각의 input에 맞도록 변수명을 수정하시거나, method 내부에서 각자 생성해서 쓰셔도 될 거 같아요

++ int 의 범위가 21억이 최대값이다 보니, 최대값이 별도로 정해지지않은 경우 
돈과 관련된 변수에서는 일반적으로 long 을 써준다고 하네요

![image](https://user-images.githubusercontent.com/41069113/104185173-f4bf5580-5457-11eb-8267-b1dbc2cbef2f.png)

2021-01-11 15:12 UTC, hhlyn0328 commented on src/main/java/lotto/InputView.java
> +        return Arrays.asList(scanner1.nextLine().split(SPLIT_TEXT));
여기에서 숫자로 변경해서 주면 좋을 거 같아요 
로또게임 입장에서는 당첨숫자 여섯자리가 들어왔다 라고 보는게 자연스러울 거 같아서 
형변환에 대한 책임은 InputView에 있는게 더 좋을 거 같아요

2021-01-11 15:12 UTC, hhlyn0328 commented on src/main/java/lotto/LottoApplication.java
> +        Price price = new Price(lottoPrice);
와우 원시값을 포장하랏! 👍

2021-01-11 15:12 UTC, hhlyn0328 commented on src/main/java/lotto/LottoGame.java
> +    private List<Lotto> lottos = new ArrayList<>();
일급 컬렉션도 활용해보면 어떨까요?

2021-01-11 15:12 UTC, hhlyn0328 commented on src/main/java/lotto/LottoGame.java
> +            lottos.add(new Lotto());
빈 로또를 인스턴스를 생성하고 다시 반복문을 돌면서 로또번호를 생성하는 것 보다
인스턴스가 생성됨과 동시에 번호를 생성하는 것은 어떨까요?

2021-01-11 15:12 UTC, hhlyn0328 commented on src/main/java/lotto/LottoApplication.java
> +        List<String> winnerNumber = InputView.inputLastLottoNumber();
당첨번호도 Lotto 아닐까요?

2021-01-11 15:12 UTC, hhlyn0328 commented on src/main/java/lotto/Lotto.java
> +        lotto = lottoNumber.getLottoNumbers().subList(0,6);
lottoNumber.getLottoNumbers().subList(0,6)

lottoNumber의 속성을 get 해서 다른 객체에서 가공(subList)하고 있어요  
lottoNumber에서 가공된 결과를 return 하도록 하면 어떨까요?
lottoNumber에게 로또번호 자동생성에 대한 모든 책임을 위임하면 
shuffle() 과 Collections.sort 도 이동할 수 있겠네요 :)

2021-01-11 15:12 UTC, hhlyn0328 commented on src/main/java/lotto/LottoNumber.java
> +    private List<Integer> lottoNumbers = Stream.iterate(1, n->n+1).limit(LOTTO_NUMBER).collect(Collectors.toList());
static 블럭이라는 것이 있어요 
적용해 본다면 List<Integer> lottoNumbers 도 static final 로 생성할 수 있게 되는데요 
그럼 클래스 함수로 로또번호를 생성하는 로직을 구현하고 호출할 수 있을 거 같습니다

2021-01-11 15:12 UTC, hhlyn0328 commented on src/main/java/lotto/LottoResult.java
> +        this.allScore = Collections.unmodifiableList(lottoScores);
unmodifiableList 👍

2021-01-11 15:12 UTC, hhlyn0328 commented on src/main/java/lotto/LottoResult.java
> +                .collect(Collectors.groupingBy(LottoScore::getScore, TreeMap::new,Collectors.counting()));
와우... groupingBy와 TreeMap을 쓰실 줄이야 👍 
collect(Collectors.groupingBy(LottoScore::getScore, TreeMap::new,Collectors.counting()))

2021-01-11 15:12 UTC, hhlyn0328 commented on src/main/java/lotto/Price.java
> +        this.price = price;
변수에 할당하기전에 checkPrice가 수행되는게 좋을 거 같아요 :)

2021-01-11 15:12 UTC, hhlyn0328 commented on src/main/java/lotto/LottoResult.java
> +        return winningAmount / Price.getPrice();
전체적인 로또 흐름을 관리하는 LottoGame이  Price를 변수로 가지고 필요한 곳에 전달하면 어떨까요?

2021-01-11 15:12 UTC, hhlyn0328 commented on src/main/java/lotto/ResultView.java
> +        System.out.println("3개 일치 (" + Reward.rewardOfScore(SCORE_3)  + "원) -" + count + "개");
System.out.println에 내부의 문장을 reward enum에게 위임할 수 있을 거 같아요 
SCORE_3 enum을 예로들면, 3개가 일치했다는 것과 당첨금액을 모두 알고 있기 때문이죠

`printScore3(getCount(lottoResult.getResult().get(SCORE_3)));`
이 아래와 같이 변경될 수 있겠네요 
`System.out.println(SCORE_3.toString() + lottoResult.get(SCORE_3) + 개);`

추가로 출력할 문자열 사이에 변수를 삽입해야하는데 변수명이 길어지면 아래와 같이 표현할 수 있는데
장점은... 표현하고자 했던 문자열 자체에 대한 가독성이 있겠습니다 

`String.format("%개 일치 (%d원) - %d 개", matchCount, price, lottoCount)`
또는
`String.format("%s - %d 개", SCORE_3.toString() , lottoCount)`

2021-01-11 15:12 UTC, hhlyn0328 commented on src/main/java/lotto/ResultView.java
> +        printScore6(getCount(lottoResult.getResult().get(SCORE_6)));
객체지향 생활체조 -> 한줄에 .은 1개만 찍는다 
2번의 .get을 사용하지 않도록 lottoResult에 method를 추가해보아용

2021-01-11 15:12 UTC, hhlyn0328 commented on src/main/java/lotto/ResultView.java
> +    private static final long SCORE_3 = 3;
상수선언없이 바로 enum을 사용해도 될 거 같아요

2021-01-11 15:12 UTC, hhlyn0328 commented on src/test/java/lotto/lottoNumberTest.java
> +        // 1장 구매시 6개의 숫자가 생성되었는지
테스트한 로직과 주석이 맞지 않아 헷갈리는거 같습니다 !

2021-01-11 15:12 UTC, hhlyn0328 commented on src/test/java/lotto/lottoTest.java
> +        List<Integer> ll = Arrays.asList(0,0,1,2,3,0) ;
이렇게 로또번호가 생성되면 안될 거 같아요 
전체적으로 validation이 필요할 거 같습니다 
당첨번호도 1,1,1,1,1,1 이 입력될 수 있을 것 같아요 

만약 당첨번호가 Lotto 객체를 재활용하게 된다면 validation 로직을 2번 구현할 필요는 없겠네요 :)

2021-01-11 15:12 UTC, hhlyn0328 commented on src/main/java/lotto/Price.java
> +    private static int price;
final은 혼자쓸 수 있지만 
static은 final 과 짝꿍으로 사용해주세용

2021-01-11 15:12 UTC, hhlyn0328 commented on src/main/java/lotto/Price.java
> +    public static int getPrice() {
이미 알고 계시겠지만, 한 번 더 상기하고 넘어가면 좋을 거 같아요
static 이 붙는 method를 클래스 함수라고 하고 static 없는 함수를 인스턴스 함수라고 해요 
클래스 함수는 new  생성자를 통해 생성하지 않아도 import해서 바로 해당 함수를 쓸 수 있는 경우이고 
인스턴스 함수는 생성 후에만 쓸 수 있죠 

일반적으로 객체 내의 '변수' 는 변할 수 있는 값으로 인스턴스를 생성하는 주체가 하고자 하는 방향대로 변하게 됩니다 
반면 '상수'는 해당 클래스의 고유한 속성으로 누가 언제 생성하든 같은 값을 가지며 변경이 불가합니다 
따라서 static이 붙은 함수는 인스턴스 생성없이 호출이 가능한 만큼 
인스턴스를 생성하는 측에 따라 변할 수 있는 변수의 접근은 지양하고 있습니다.

2021-01-12 00:01 UTC, eeunheechoi commented on src/main/java/lotto/InputView.java
> +        return scanner.nextInt();
nextLine으로 변경합니다.

2021-01-12 00:06 UTC, eeunheechoi commented on src/main/java/lotto/InputView.java
> +        return Arrays.asList(scanner1.nextLine().split(SPLIT_TEXT));
네

2021-01-12 00:26 UTC, eeunheechoi commented on src/main/java/lotto/InputView.java
> +        return Arrays.asList(scanner1.nextLine().split(SPLIT_TEXT));
형변환에 애를 먹었는데.. 맞게 했는지 모르겠네요

2021-01-12 00:29 UTC, eeunheechoi commented on src/main/java/lotto/LottoGame.java
> +            lottos.add(new Lotto());
lotto 생성자에 createLotto를 호출하도록 변경합니다.

2021-01-12 00:29 UTC, eeunheechoi commented on src/main/java/lotto/LottoApplication.java
> +        List<String> winnerNumber = InputView.inputLastLottoNumber();
Lotto로 변경합니다

2021-01-12 00:36 UTC, eeunheechoi commented on src/main/java/lotto/Lotto.java
> +        lotto = lottoNumber.getLottoNumbers().subList(0,6);
네 lottoNumber에 번호생성 역할을 넘기도록 합니다.

2021-01-12 00:44 UTC, eeunheechoi commented on src/main/java/lotto/LottoNumber.java
> +    private List<Integer> lottoNumbers = Stream.iterate(1, n->n+1).limit(LOTTO_NUMBER).collect(Collectors.toList());
내부 메소드 다 빼고 static {} 안에 로직을 넣었는데 맞는건지 모르겠네요

2021-01-12 00:46 UTC, eeunheechoi commented on src/main/java/lotto/Price.java
> +        this.price = price;
네

2021-01-12 00:51 UTC, eeunheechoi commented on src/main/java/lotto/LottoResult.java
> +        return winningAmount / Price.getPrice();
네

2021-01-12 01:35 UTC, eeunheechoi commented on src/main/java/lotto/ResultView.java
> +        System.out.println("3개 일치 (" + Reward.rewardOfScore(SCORE_3)  + "원) -" + count + "개");
reward enum에게 무얼 위임해야 하는지 감이 안와서.. 일단 수정은 했는데..
다시 코멘트 줄거 같아요. ㅎㅎ

2021-01-12 01:36 UTC, eeunheechoi commented on src/main/java/lotto/ResultView.java
> +        printScore6(getCount(lottoResult.getResult().get(SCORE_6)));
나름 수정해 봅니다.

2021-01-12 01:54 UTC, eeunheechoi commented on src/main/java/lotto/ResultView.java
> +    private static final long SCORE_3 = 3;
enum을 바로 사용하면 Long.parseLong(Reward.SCORE_3.toString()) 이렇게 길어지는게 이걸 요구하는게 맞나요? 잘못이해 했을가요?

2021-01-12 01:58 UTC, eeunheechoi commented on src/test/java/lotto/lottoNumberTest.java
> +        // 1장 구매시 6개의 숫자가 생성되었는지
주석 변경 및 테스트 내용 보충합니다.

2021-01-12 02:59 UTC, eeunheechoi commented on src/test/java/lotto/lottoTest.java
> +        List<Integer> ll = Arrays.asList(0,0,1,2,3,0) ;
중복체크 로직 추가합니다

2021-01-12 03:03 UTC, eeunheechoi commented on src/main/java/lotto/Price.java
> +    private static int price;
네 final 선언만 하도록 합니다. 

final로 선언하면 초기값을 생성자에서 해도 되는데, static final로 선언하면 선언과 동시에 초기값도 정의해야 한다고 하고..
0으로 초기화 하고 생성자에서 다시 재정의 할 수 없다고 하는데.. 
언제 static으로 선언을 해야 하는건지 감이 잘 오지 않아요..

2021-01-12 03:10 UTC, eeunheechoi commented on src/main/java/lotto/Price.java
> +    public static int getPrice() {
요런 설명 참 좋습니다

2021-01-12 03:42 UTC, eeunheechoi commented on src/main/java/lotto/LottoGame.java
> +    private List<Lotto> lottos = new ArrayList<>();
음 만들어서 어떤 용도로 써야 할지 모르게써요.. 
LottoScore와 LottoResult에 로또 결과를 가지도록 했는데.. 
음.. 좀 더 설명 부탁욤

2021-01-12 14:09 UTC, hhlyn0328 requested changes
커밋이 첫번째 리뷰반영이라고 되어있어서 조금 터졋네요 ㅋㅋㅋ
이번에 드린 코멘트가 저번 코멘트에서 애매했던 부분을 조금 해소해드릴 수 있으면 좋겠네요 🤔 
이번에는 하다가 막히면 슬랙주세욥!

굳이..? 싶은 코멘트도 있을 수 있어요 
이러이런 생각에 굳이 해야할까 싶어서 반영 안했다! 라고 코멘트 달아주시면 
저도 의견을 받을 수 있으니 편하게 선택해서 해주세요 ㅋㅋ

2021-01-12 14:09 UTC, hhlyn0328 commented on src/main/java/lotto/InputView.java
> +        List<String> arr = new ArrayList<>(Arrays.asList(lottoNumber));
`Arrays.stream(lottoNumber).map().collect()`
위의 문법으로 배열 스트림 처리가 가능합니다 
한 번 활용해보시면 좋을 거 같아요

이 함수에서 아예 Lotto형태로 return 해주는건 어떨까요? (그렇다면 method명도 변경되면 좋겠죠?)
변경된다면 inputLastLottoNumber method의 return 문이 좀 더 간단해질 수 있을 거 같아요

2021-01-12 14:09 UTC, hhlyn0328 commented on src/main/java/lotto/LottoNumber.java
>          Collections.shuffle(lottoNumbers);
사실 전 처음에 이렇게 구현했었는데요 
상수는 초기화를 정적으로 빡! 해줘야한다는 강박관념 때문이었어요
그에 반해 은희님은 아주 인텔리하게 작성하셨네요 😅 
저처럼 하면 문제는 만약에 로또가 숫자가 100까지로 늘었다! 했을 때 답이 없죠...
```
private static final List<Integer> LOTTO_TOTAL_NUMBERS = Arrays.asList(
1, 2, 3, 4, 5, ..... 43, 44, 45);
```

저 노답코드를 보고 리뷰어 분이 static 블럭을 한 번 써보면 어떻겠냐 했고
보통 static final은 선언하면 끗- 이라는 생각이었는데 
아래처럼 표현하면 초기화 선언 후, 가공해도 은희님 처럼 초기화 한 것과 같은 결과가 나오는거죠 
차이는 조금의 가독성 증가..? 정도...

```
private static final List<Integer> LOTTO_TOTAL_NUMBERS = new ArrayList<>();
private static final int MIN_NUMBER = 1;
private static final int MAX_NUMBER = 45;

static {
	for (int i = MIN_NUMBER; i <= MAX_NUMBER; i++) {
		LOTTO_TOTAL_NUMBERS.add(i);
	}
}
```

2021-01-12 14:09 UTC, hhlyn0328 commented on src/main/java/lotto/Lotto.java
> +        lotto = new LottoNumber().pickLottoNumber();
new LottoNumber().pickLottoNumber()
현재 로또번호 생성을 인스턴스 함수로 사용하고 있는데 
이는 1-45를 갖는 배열을 로또의 수만큼 생성하게 되는데요

클래스 함수로 사용해보면 어떨까요?

2021-01-12 14:09 UTC, hhlyn0328 commented on src/main/java/lotto/Lotto.java
> +    public void duplicationNumber() {
생성자가 `List<Integer>`인 만큼 로또번호를 생성하고자 하는 input이 다양하게 들어올 수 있을 거 같아요 
자동 생성은, 1-45 로 막히겠지만  당첨번호는  [-1, 57] 과 같은 형태도 생성될 것 같은데 
로또번호의 제약을 모두 검증해주면 어떨까요? 1 - 45 / 중복없이 / 6자리

2021-01-12 14:09 UTC, hhlyn0328 commented on src/main/java/lotto/LottoGame.java
> +    private List<Lotto> lottos = new ArrayList<>();
일급 컬렉션이 추가된다면 아래 matching내부 로직이 그 안으로 이동하게 될 거 같아요
전체 로또번호라는 이야기니 당첨번호는 이건데 전체적인 결과가 어떻게 돼? 라고 책임을 위임하는 거죠
그저 그 부분도 써볼 수 있다- 하는 거지 이거는 선택사항입니다 ㅋㅋ

2021-01-12 14:09 UTC, hhlyn0328 commented on src/main/java/lotto/LottoResult.java
> +    private int lottoPrice;
포장된 원시값이 다시 풀어져서 변수로 쓰이고 있네요
Price 객체를 가지도록 변경하고 Price.getPrice() 를 통해 꺼내온 뒤에 밖에서 계산하지말고 
수익률 계산을 Price에게 위임하면 어떨까요? `총 당첨금이 이건데 구매금액기준으로 수익률은 얼마야?`

2021-01-12 14:09 UTC, hhlyn0328 commented on src/test/java/lotto/lottoGamesTest.java
> +        List<Integer> lt1 = Arrays.asList(0,0,1,2,3,0) ;
로또 번호 중복체크 로직 추가되면서 이 테스트는 실패했을 거 같은데요 🤔 
항상 리팩토링 후에는 전체 테스트를 초록불 유지할 수 있도록 테스트코드도 유지보수해주세요 🙏

2021-01-12 14:09 UTC, hhlyn0328 commented on src/main/java/lotto/ResultView.java
> +        System.out.printf("%f개 일치 (%f 원) - %f 개", SCORE_3, lottoResult.getReward(SCORE_3), lottoResult.getCount(SCORE_3));
System.out.printf("%f개 일치 (%f 원) - %f 개", **Reward.score**, **Reward.reward**, lottoResult.getCount(**Reward.score**));

위의 로직은 규칙적으로 반복되는 것으로 보이는데 제거해보고 싶지 않으실까요?ㅋㅋㅋ
Reward에서 keySet을 호출하면 등록한 순서대로 호출되게됩니다 (찝찝하면 keySet().stream().sort() 하셔도돼요)
SCORE_0 을 제외한 keySet을 반환하는 로직을 Reward에 추가하면 어떨까요?
그 keySet을 기준으로 반복문을 돌며 출력하게 되면 ResultView 상단에 선언한 상수들이 사라질 수 있지 않을까요?

단순히 코드 라인을 줄인다는 목적보다는
일치하는 숫자에 따른 reward의 매핑을 Reward enum이 담당하고 있기 때문에 
매칭 숫자 기준을 반복적으로 선언하는 것보다 이미 정의 된 값을 재활용해 보면 좋을 것 같아서요 

+++추가적으로+++ 정의한 Enum을 좀 더 활용해 볼까요?

Lotto.maching 의 return type을 Reward 로 변경해보는건 어떨까요?
단순 당첨 숫자와 일치한 갯수가 뿐만 아니라  그 보상 자체를 알려주는거죠
해당 변경점이 전파되고 전파되다 보면  위의 코드의 getCount의 키가 바뀔수도 있을 것 같네요 😉 
lottoResult.getCount(**???**)

2021-01-12 14:10 UTC, hhlyn0328 commented on src/main/java/lotto/ResultView.java
> +    private static final long SCORE_3 = 3;
enum사용에 대해 추가 코멘트 달았습니다 
https://github.com/hhlyn0328/lotto-practice/pull/6#discussion_r555774741 참고해주세용

2021-01-12 14:11 UTC, hhlyn0328 commented on src/main/java/lotto/ResultView.java
> +        System.out.println("3개 일치 (" + Reward.rewardOfScore(SCORE_3)  + "원) -" + count + "개");
enum사용에 대해 추가 코멘트 달았습니다
#6 (comment) 참고해주세용

2021-01-12 14:13 UTC, hhlyn0328 commented on src/main/java/lotto/LottoNumber.java
> +    private List<Integer> lottoNumbers = Stream.iterate(1, n->n+1).limit(LOTTO_NUMBER).collect(Collectors.toList());
static 블럭에 대한 코멘트 추가했습니다
https://github.com/hhlyn0328/lotto-practice/pull/6#discussion_r555706816

2021-01-12 14:15 UTC, hhlyn0328 commented on src/main/java/lotto/InputView.java
> +        return Arrays.asList(scanner1.nextLine().split(SPLIT_TEXT));
Array와 List 사이의 변환이 조금 헷갈리죠 
관련해서 코멘트 추가했습니다 참고해도 원하는 대로 잘 안된다 하시면 DM 주세용
https://github.com/hhlyn0328/lotto-practice/pull/6#discussion_r555703007

2021-01-12 14:16 UTC, hhlyn0328 commented on src/main/java/lotto/InputView.java
> +        return scanner.nextInt();
제가 가이드를 Integer.parseInt로 드렸는데 
price가 long이 되었으니 Long.parseLong 이 있다면 그걸 사용하는게 더 좋겠네요 😅

2021-01-12 14:33 UTC, hhlyn0328 commented on src/test/java/lotto/lottoTest.java
> +    void lotto_숫자중복_test() {
추가된 로직에 대한 테스트 코드도 열심히 작성해주셨네요 👍

2021-01-13 01:41 UTC, eeunheechoi commented on src/main/java/lotto/InputView.java
> +        List<String> arr = new ArrayList<>(Arrays.asList(lottoNumber));
네 반영합니다

2021-01-13 01:46 UTC, eeunheechoi commented on src/main/java/lotto/LottoNumber.java
>          Collections.shuffle(lottoNumbers);
네

2021-01-13 01:47 UTC, eeunheechoi commented on src/main/java/lotto/Lotto.java
> +        lotto = new LottoNumber().pickLottoNumber();
pickLottoNumber() 에 static을 선언합니다.

2021-01-13 03:32 UTC, eeunheechoi commented on src/main/java/lotto/Lotto.java
> +    public void duplicationNumber() {
검증로직 추가합니다.

2021-01-13 03:36 UTC, eeunheechoi commented on src/main/java/lotto/LottoResult.java
> +    private int lottoPrice;
price에서 수익률을 가져오도록 합니다.

2021-01-13 03:38 UTC, eeunheechoi commented on src/test/java/lotto/lottoGamesTest.java
> +        List<Integer> lt1 = Arrays.asList(0,0,1,2,3,0) ;
테스트용 생성자여서 검증로직을 타지 않았어요.
lottoNumber에 숫자 검증로직을 넣었어요

2021-01-14 08:09 UTC, updown-kurly commented on src/main/java/lotto/Lotto.java
> +        if(lotto.size() != 6) {
6도 상수로 뺄 수 있을것 같습니다.

2021-01-14 08:11 UTC, updown-kurly commented on src/main/java/lotto/Lotto.java
> +        List<Integer> dupList = lotto.stream().distinct().collect(Collectors.toList());
stream 다음에 한줄 넘어가면 좋을것 같습니다!

2021-01-14 15:41 UTC, updown-kurly commented on src/main/java/lotto/Lotto.java
> +        if(minusNumCount > 0) {
0 상수로 빼면 좋을것 같아요

2021-01-14 15:44 UTC, updown-kurly commented on src/main/java/lotto/Price.java
> +            throw new RuntimeException("최소 게임 금액음 1000원입니다. ");
Exception 메시지가 PRICE_PER_GAME 값이 변경되면 같이 변경 되어야 할 것 같습니다

2021-01-14 15:45 UTC, updown-kurly commented on src/main/java/lotto/ResultView.java
> +        System.out.println("총 수익률은 " + lottoResult.winningRate() + "입니다.");
요건 질문인데 이렇게 뽑아도 0.35 이런식으로 나오나요?

2021-01-14 15:49 UTC, updown-kurly commented on src/main/java/lotto/InputView.java
> +                .map(a -> Integer.parseInt(a))
변수명이 a 로 되어있어서 하나의 로또 번호를 나타내줄수 있는 변수명이면 가독성이 조금 더 좋을것 같습니다!

2021-01-14 15:57 UTC, updown-kurly commented on src/main/java/lotto/LottoResult.java
> +        this.allScore = Collections.unmodifiableList(lottoScores);
앗 이거 안했는데...

2021-01-14 16:05 UTC, updown-kurly commented on src/main/java/lotto/Lotto.java
> +                .filter(number -> number < LottoNumber.getMinNumber() || number > LottoNumber.getMaxNumber())
클린코드는 일단 다른 인스턴스에서 get한 값을 쓰는걸 정말 어쩔 수 없는 경우를 빼고는 지양한다고 하는데...
이건 어떻게 풀어 나갈수 있을까요 ( 저도 해결해나가야 하는 문제... )

2021-01-14 16:08 UTC, updown-kurly commented on src/main/java/calulator/StringAddCalculator.java
> +        int sum=0;
이건 별건 아니긴 한대 변수 선언시에
int i=0;
int i = 0;
이런 포멧을 저는 google formatter 를 설치하여 command + option + L 단축키로 항상 통일시키고 있습니당

2021-01-14 16:10 UTC, updown-kurly commented on src/main/java/lotto/LottoGame.java
> +    public LottoGame(List<Lotto> lottoList,Price price) {// test용 생성자
저 같은 경우에는 Test 에서만 사용할 친구들은 protected 접근제어자를 사용하였습니다

2021-01-14 16:18 UTC, updown-kurly commented on src/test/java/lotto/lottoNumberTest.java
> +        List<Integer> ll = Arrays.asList(1,2,3,4,5) ;
이건 제가 유익했던 내용인데 여기에 1자리 2자리 3자리 4자리 7자리 가 추가된다면 이런식으로 쓰면 깔끔하게 쓸수 있다고 합니다

    @ParameterizedTest
    @MethodSource("generateData")
    void 번호가_6자리_Exception테스트(List<Integer> numbers) {
        assertThatExceptionOfType(IllegalArgumentException.class).isThrownBy(() -> {
            new LottoNumber(numbers);
        });
    }

    static Stream<Arguments> generateData() {
        return Stream.of(
                Arguments.of(Arrays.asList(1)),
                Arguments.of(Arrays.asList(1, 2)),
                Arguments.of(Arrays.asList(1, 2, 3)),
                Arguments.of(Arrays.asList(1, 2, 3, 4)),
                Arguments.of(Arrays.asList(1, 2, 3, 4, 5)),
                Arguments.of(Arrays.asList(1, 2, 3, 4, 5, 6, 7))
                );
    }

2021-01-17 00:34 UTC, hhlyn0328 commented on src/main/java/lotto/Lotto.java
> +                .filter(number -> number < LottoNumber.getMinNumber() || number > LottoNumber.getMaxNumber())
@updown-kurly 좋은 의견 남겨주셨네요 
보통은 get을 해오는 객체에 반대로 값을 넘겨주어서 협업하는 방법으로 해결합니다 
이 경우도 LottoNumber에 isValidRange 등과 같은 method를 만들고 number를 넘겨주게 되면 getter없이 해결이 될 수 있겠네요 :)

2021-01-17 00:53 UTC, hhlyn0328 approved these changes
Enum 활용 굿입니다 👍 
거의 마무리 되었는데 getter 함께 쓰는 로직만 전체적으로 한 번 확인해봐주시면 좋을 거 같습니다 
다음 커밋후에는 머지하고 다음 미션 가시죠 !

2021-01-17 00:53 UTC, hhlyn0328 commented on src/main/java/lotto/LottoGame.java
> +            lottoScores.add(new LottoScore(lotto, lotto.matching(winnerNumber)));
위와 같이 `List<A> -> List<B> `변환을 하는 경우는 stream.map을 사용해보는 연습을 적극 해보는 것도 좋을 거 같아요 !
lottos.stream.map(lotto -> new LottoScore).collect

2021-01-17 00:53 UTC, hhlyn0328 commented on src/main/java/lotto/LottoResult.java
> +                .filter(lottoScore -> !Reward.SCORE_0.equals(lottoScore.getReward()) )
이런 부분도 lottoScore.isNoReward()  와 같이 get을 이용해 꺼내서 밖에서 비교하지 않고 
객체에게 문의하라고 코멘트를 받곤 합니다 (7주째 매주 받고 있어요 .. ㅋㅋㅋ 중이 제 머리는 못 깎는다죠.. 후..)

private boolean isNoReward() {
     return Reward.SCORE_0.equals(this.reward);
}

2021-01-17 00:53 UTC, hhlyn0328 commented on src/main/java/lotto/LottoScore.java
> +    private Reward reward;
클래스 변수는 상단으로 !

2021-01-19 00:32 UTC, eeunheechoi commented on src/main/java/lotto/Lotto.java
> +        if(lotto.size() != 6) {
네

2021-01-19 00:33 UTC, eeunheechoi commented on src/main/java/lotto/Lotto.java
> +        if(lotto.size() != 6) {
네

2021-01-19 00:33 UTC, eeunheechoi commented on src/main/java/lotto/Lotto.java
> +        if(minusNumCount > 0) {
네

2021-01-19 00:34 UTC, eeunheechoi commented on src/main/java/lotto/Lotto.java
> +        List<Integer> dupList = lotto.stream().distinct().collect(Collectors.toList());
네

2021-01-19 00:35 UTC, eeunheechoi commented on src/main/java/lotto/Price.java
> +            throw new RuntimeException("최소 게임 금액음 1000원입니다. ");
네

2021-01-19 00:35 UTC, eeunheechoi commented on src/main/java/lotto/ResultView.java
> +        System.out.println("총 수익률은 " + lottoResult.winningRate() + "입니다.");
네

2021-01-19 00:38 UTC, eeunheechoi commented on src/main/java/lotto/InputView.java
> +                .map(a -> Integer.parseInt(a))
네

2021-01-19 00:50 UTC, eeunheechoi commented on src/main/java/lotto/Lotto.java
> +                .filter(number -> number < LottoNumber.getMinNumber() || number > LottoNumber.getMaxNumber())
네

2021-01-19 00:50 UTC, eeunheechoi commented on src/main/java/calulator/StringAddCalculator.java
> +        int sum=0;
네

2021-01-19 00:51 UTC, eeunheechoi commented on src/main/java/lotto/LottoGame.java
> +    public LottoGame(List<Lotto> lottoList,Price price) {// test용 생성자
네

2021-01-19 00:54 UTC, eeunheechoi commented on src/test/java/lotto/lottoNumberTest.java
> +        List<Integer> ll = Arrays.asList(1,2,3,4,5) ;
네

2021-01-19 00:57 UTC, eeunheechoi commented on src/main/java/lotto/LottoGame.java
> +            lottoScores.add(new LottoScore(lotto, lotto.matching(winnerNumber)));
네

2021-01-19 01:00 UTC, eeunheechoi commented on src/main/java/lotto/LottoResult.java
> +                .filter(lottoScore -> !Reward.SCORE_0.equals(lottoScore.getReward()) )
네

2021-01-19 01:01 UTC, eeunheechoi commented on src/main/java/lotto/LottoScore.java
> +    private Reward reward;
네

2021-01-19 04:12 UTC, hhlyn0328 approved these changes
👏 
고생하셨습니다 
지금 남긴 코멘트는 다음 미션에서 참고만해주세요 !

2021-01-19 04:12 UTC, hhlyn0328 commented on src/main/java/lotto/LottoGame.java
> +        lottoScores = lottos.stream()
List<LottoScore> lottoScores = new ArrayList<>();
라인 지우고 
List<LottoScore> lottoScores = lottos.stream()
으로 갈 수 있겠네요 !

2021-01-19 04:12 UTC, hhlyn0328 commented on src/main/java/lotto/Lotto.java
> +        isDupulicationNumber();
보통 동사로 method 명을 지정할 때,
is 가 앞에 붙는 경우는 boolean 형을 return 할때 입니다 
이런, 유효하지 않은경우 exception을 던지는 함수는 validate 또는 check 정도의 동사를 붙여주시면 좋을 거 같아요

2021-01-19 04:14 UTC, merged