feat: 로또 2등 추첨 기능 개발
hhlyn0328/lotto-practice pull request #8
Opened 2021-01-24 01:37 UTC by updown-kurly

2021-01-25 03:03 UTC, eeunheechoi approved these changes
수고하셨습니다!!
혜린님이 보다 풍푸하고 알찬 내용의 리뷰를 추가해 주실겁니다. ㅎㅎ

2021-01-25 03:03 UTC, eeunheechoi commented on src/main/java/lotto/LottoRank.java
> +    SECOND(5, 30000000, true),
SECOND 왜 true 값을 가지나요?

2021-01-25 03:03 UTC, eeunheechoi commented on src/main/java/lotto/InputView.java
> +                .map(Integer::parseInt)
good!

2021-01-25 03:03 UTC, eeunheechoi commented on src/main/java/lotto/LottoWinnerNumber.java
> +        return new LottoResult(lottoNumber.matchCount(this.lottoWinnerNumber), lottoNumber.isContains(this.lottoWinnerBonusNumber));
LottoResult가 애초에 Rank를 가지면 matchCount알고 있기 때문에 LottoTotalResult에서 금액을 뽑아 낼때 로직이 간단해 질거 같습니다.

2021-01-25 03:03 UTC, eeunheechoi commented on src/main/java/lotto/LottoTotalResult.java
> +            return;
lottoResult가 rank를 가진다면 이렇게 판단하지 않아도 될 거 같아요
rank의 matchCount로 바로 알 수 있을 거 같습니다.

2021-01-25 03:03 UTC, eeunheechoi commented on src/main/java/lotto/LottoNumber.java
> +    public int matchCount(LottoNumber lottoWinnerNumber) {
rank를 찾아 리턴한다면 lottoResult는 Rank를 가지게 될 거 같습니다.
lottoResult로 matchCount를 판별하는 로직이 아래 있던데
lottoResult 가 Rank를 가진다면 바로 matchCount를 알 수 있을 거 같습니다.

2021-01-25 03:03 UTC, eeunheechoi commented on src/main/java/lotto/LottoApplication.java
> +        LottoWinnerNumber lottoWinnerNumber = InputView.scannerLastWeekLottoNumber();
우승번호와 서비스 번호를 한번에 생성하니 메인 로직이 깔금하네요. 저도 참조하겠습니다.

2021-01-25 07:15 UTC, updown-kurly commented on src/main/java/lotto/LottoRank.java
> +    SECOND(5, 30000000, true),
3번째 인자값으로 보너스번호 일치여부를 구분하였습니다

2021-01-25 07:20 UTC, updown-kurly commented on src/main/java/lotto/LottoWinnerNumber.java
> +        return new LottoResult(lottoNumber.matchCount(this.lottoWinnerNumber), lottoNumber.isContains(this.lottoWinnerBonusNumber));
감사합니다!

2021-01-25 08:06 UTC, updown-kurly commented on src/main/java/lotto/LottoTotalResult.java
> +            return;
넵!

2021-01-25 08:07 UTC, updown-kurly commented on src/main/java/lotto/LottoNumber.java
> +    public int matchCount(LottoNumber lottoWinnerNumber) {
넵!

2021-01-27 01:37 UTC, hhlyn0328 requested changes
고생하셨습니다 
꼭 개선해야할 사항이 아니라 참고사항 정도라서 머지할까 하다가 
한 개 예외사항이 마음에 걸려서 changeRequest 드리겠습니다 
해당 경우 테스트해보시고, 예상치못한 결과가 발생한다면 수정부탁드려요 :)

2021-01-27 01:37 UTC, hhlyn0328 commented on src/main/java/lotto/LottoNumber.java
> +    public List<Integer> validations(List<Integer> lottoNumber) {
method 는 특정 행위를 수행하므로 동사로 시작하는 것이 일반적인 naming rule 이니 참고해주세요 :)

2021-01-27 01:37 UTC, hhlyn0328 commented on src/main/java/lotto/LottoNumber.java
>      protected LottoNumber(List<Integer> lottoNumber) {
`null` 로 생성을 시도하면 어떻게 되나요?

2021-01-27 01:37 UTC, hhlyn0328 commented on src/main/java/lotto/LottoNumbers.java
>          return lottoTotalResult;
`return new LottoTotalResult(lottoResults);`
로 더 간단히 표현할 수 있을 거 같아요

2021-01-27 01:37 UTC, hhlyn0328 commented on src/main/java/lotto/LottoRank.java
> +                .filter(value -> value.countOfMatch == countOfMatch && value.matchBonus == matchBonus)
lottoNumber = 1,2,3,4,5,6
winnerNumber = 1,2,3,43,44,45
bonusNumber = 4

위의 경우는 5등을 찾아주나요?

2021-01-27 01:37 UTC, hhlyn0328 commented on src/main/java/lotto/LottoTotalResult.java
> +                .sum();
결국 lottoRank의 winningMoney * matchCount 들의 합일 거 같은데 
totalMatchCountMap에 Put하는 과정에서 계산할 수 있지 않을까요?

2021-01-27 01:37 UTC, hhlyn0328 commented on src/main/java/lotto/LottoWinnerNumber.java
> +        validations();
인스턴스 변수를 셋팅하기 전에 validation 을 먼저 수행하는것이 맞지 않을까요?

2021-01-27 05:28 UTC, updown-kurly commented on src/main/java/lotto/LottoNumbers.java
>          return lottoTotalResult;
넵!

2021-01-27 05:28 UTC, updown-kurly commented on src/main/java/lotto/LottoTotalResult.java
> +                .sum();
넵넵!

2021-01-27 05:28 UTC, updown-kurly commented on src/main/java/lotto/LottoNumber.java
> +    public List<Integer> validations(List<Integer> lottoNumber) {
넵!

2021-01-27 05:34 UTC, updown-kurly commented on src/main/java/lotto/LottoNumber.java
>      protected LottoNumber(List<Integer> lottoNumber) {
NullpointerException이 발생 하고 있었으나 좀 더 명확하게 예외처리를 하기위해
length 판별하는 로직에 null 조건을 or 로 추가하였습니다.

2021-01-27 05:34 UTC, updown-kurly commented on src/main/java/lotto/LottoNumbers.java
>          return lottoTotalResult;
넵!

2021-01-27 05:35 UTC, updown-kurly commented on src/main/java/lotto/LottoTotalResult.java
> +                .sum();
넵넵!

2021-01-27 08:05 UTC, updown-kurly commented on src/main/java/lotto/LottoRank.java
> +                .filter(value -> value.countOfMatch == countOfMatch && value.matchBonus == matchBonus)
아니요....

2021-01-28 05:22 UTC, hhlyn0328 approved these changes
간단한 코멘트 남겼는데 이 내용은 다음 미션하면서 참고해주세요 
고생하셨습니다 :) 
로또 마지막까지! 화이팅

2021-01-28 05:22 UTC, hhlyn0328 commented on src/main/java/lotto/LottoNumber.java
> +    private  int LOTTO_START_NUMBER = 1;
static final을 왜 지우셨을까요?
클래스 상수는 항상 고정된 값으로 변경이 불가해야합니다

2021-01-28 05:22 UTC, hhlyn0328 commented on src/main/java/lotto/LottoRank.java
>                  .filter(value -> value.countOfMatch == countOfMatch && value.matchBonus == matchBonus)
matchBonusRequireLottoRank 이므로 
value.matchBonus == matchBonus 비교 없이  && matchBonus 만 체크하면 될 거 같아요

2021-01-28 05:22 UTC, hhlyn0328 commented on src/test/java/lotto/LottoResultTest.java
> +//        LottoWinnerNumber lottoWinnerNumber = new LottoWinnerNumber(Arrays.asList(1, 2, 3, 4, 5, 6), 7);
주석 제거-

2021-01-28 05:23 UTC, merged